#! /Users/marcgile/miniforge3/bin/python
#! /usr/bin/python
import argparse
import pathlib
import sys
import timeit

import amplpy

AMPL_PATH = '/Users/marcgile/SourceProgs/ampl/ampl'

models = {
    'sll':   ['ampl/sll1.mod',   'ampl/sll2.mod'  ],
    'efsll': ['ampl/efsll1.mod', 'ampl/efsll2.mod'],
}

def getampl():
    amplpy.add_to_path(AMPL_PATH)
    ampl = amplpy.AMPL()
    ampl.option['solver'    ] = 'cplex'
    ampl.option['solver_msg'] = '0'
    return ampl

def parseargs():
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', '--form',    default='efsll')
    parser.add_argument('-d', '--datadir', default='01')
    args = parser.parse_args()

    return args.form, args.datadir

def getdata(form, datadir):
    datapath = pathlib.Path('data') / form / datadir

    if not datapath.is_dir():
        sys.exit(1)

    instances = []
    for instance in datapath.iterdir():
        instances += [
            str(instance)
        ]

    return instances

def parse_solve_message(msg):
    msg = msg.split('\n')[1]
    msg = msg.split(' ' )[0]
    return int(msg)

def runsolver(form, instances):
    results = []
    for model in models[form]:
        model_res = []
        for instance in instances:
            info = []
            
            ampl.reset()
            ampl.read     ('ampl/efsll2.mod')
            ampl.read_data(instance)
            time = timeit.timeit(
                stmt  =lambda: ampl.eval('solve > /dev/null;'),
                number=1
            )

            nodes = parse_solve_message(ampl.get_value('solve_message'))
            sol   =                     ampl.get_value('Gains')
            
            model_res += [[nodes, time, sol]]
        results += [model_res]

    return results

def printrawresults(form, datadir, results):
    print(results)

def printlatextables(form, datadir, results):
    pass

def printplots(form, datadir, results):
    pass

if __name__ == '__main__':
    ampl          = getampl  ()
    form, datadir = parseargs()
    instances     = getdata  (form, datadir)
    
    results = runsolver(form, instances)

    printrawresults (form, datadir, results)
    printlatextables(form, datadir, results)
    printplots      (form, datadir, results)
